version: "3.5"

services:
  n8n:
    image: 683390223851.dkr.ecr.eu-west-1.amazonaws.com/elp-prod-n8n:v2
    # build:
    #   context: ../
    #   dockerfile: Dockerfile
    env_file:
      - ../.env.local
    ports:
      - 5678:5678
    volumes:
      - ../.n8n:/home/node/.n8n