version: "3.5"

services:
  n8n:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - ../.env.local
    ports:
      - 5678:5678
    volumes:
      - ../.n8n:/home/node/.n8n